// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GameStateType.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace pbs {

  /// <summary>Holder for reflection information generated from GameStateType.proto</summary>
  public static partial class GameStateTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for GameStateType.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GameStateTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNHYW1lU3RhdGVUeXBlLnByb3RvKj4KDUdhbWVTdGF0ZVR5cGUSCwoHSW52",
            "YWxpZBAAEgkKBUxvZ2luEAESCQoFTG9iYnkQAhIKCgZCYXR0bGUQA0ILWgNt",
            "c2eqAgNwYnNiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::pbs.GameStateType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum GameStateType {
    [pbr::OriginalName("Invalid")] Invalid = 0,
    [pbr::OriginalName("Login")] Login = 1,
    [pbr::OriginalName("Lobby")] Lobby = 2,
    [pbr::OriginalName("Battle")] Battle = 3,
  }

  #endregion

}

#endregion Designer generated code
