// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Test.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace pbs {

  /// <summary>Holder for reflection information generated from Test.proto</summary>
  public static partial class TestReflection {

    #region Descriptor
    /// <summary>File descriptor for Test.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TestReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpUZXN0LnByb3RvGhFMb2dpbkNvbW1vbi5wcm90bxoQSXRlbUNvbW1vbi5w",
            "cm90bxoKTWFpbC5wcm90byKXAQoKUmVxVGVzdE1zZxIPCgdhY2NvdW50GAEg",
            "ASgJEhAKCHBhc3N3b3JkGAIgASgJEiAKCHpvbmVsaXN0GAMgAygLMg4uTG9n",
            "aW5ab25lTGlzdBIfCgxtYWlsZGF0YWxpc3QYBCADKAsyCS5NYWlsRGF0YRIj",
            "CgxpdGVtaW5mb2xpc3QYBSADKAsyDS5CYXNlSXRlbUluZm8iQgoNUmVxVGVz",
            "dEcyRE1zZxIPCgdhY2NvdW50GAEgASgJEiAKCHpvbmVsaXN0GAIgAygLMg4u",
            "TG9naW5ab25lTGlzdCJCCg1SZXFUZXN0RDJHTXNnEg8KB2FjY291bnQYASAB",
            "KAkSIAoIem9uZWxpc3QYAiADKAsyDi5Mb2dpblpvbmVMaXN0InQKClJzcFRl",
            "c3RNc2cSIAoIem9uZWxpc3QYASADKAsyDi5Mb2dpblpvbmVMaXN0Eh8KDG1h",
            "aWxkYXRhbGlzdBgCIAMoCzIJLk1haWxEYXRhEiMKDGl0ZW1pbmZvbGlzdBgD",
            "IAMoCzINLkJhc2VJdGVtSW5mb0ILWgNtc2eqAgNwYnNiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::pbs.LoginCommonReflection.Descriptor, global::pbs.ItemCommonReflection.Descriptor, global::pbs.MailReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::pbs.ReqTestMsg), global::pbs.ReqTestMsg.Parser, new[]{ "Account", "Password", "Zonelist", "Maildatalist", "Iteminfolist" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::pbs.ReqTestG2DMsg), global::pbs.ReqTestG2DMsg.Parser, new[]{ "Account", "Zonelist" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::pbs.ReqTestD2GMsg), global::pbs.ReqTestD2GMsg.Parser, new[]{ "Account", "Zonelist" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::pbs.RspTestMsg), global::pbs.RspTestMsg.Parser, new[]{ "Zonelist", "Maildatalist", "Iteminfolist" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ReqTestMsg : pb::IMessage<ReqTestMsg> {
    private static readonly pb::MessageParser<ReqTestMsg> _parser = new pb::MessageParser<ReqTestMsg>(() => new ReqTestMsg());
    private pb::UnknownFieldSet _unknownFields;
    public const ulong HashID = 0x428F6DD970333F56;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ReqTestMsg> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::pbs.TestReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReqTestMsg() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReqTestMsg(ReqTestMsg other) : this() {
      account_ = other.account_;
      password_ = other.password_;
      zonelist_ = other.zonelist_.Clone();
      maildatalist_ = other.maildatalist_.Clone();
      iteminfolist_ = other.iteminfolist_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReqTestMsg Clone() {
      return new ReqTestMsg(this);
    }

    /// <summary>Field number for the "account" field.</summary>
    public const int AccountFieldNumber = 1;
    private string account_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Account {
      get { return account_; }
      set {
        account_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "password" field.</summary>
    public const int PasswordFieldNumber = 2;
    private string password_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Password {
      get { return password_; }
      set {
        password_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "zonelist" field.</summary>
    public const int ZonelistFieldNumber = 3;
    private static readonly pb::FieldCodec<global::pbs.LoginZoneList> _repeated_zonelist_codec
        = pb::FieldCodec.ForMessage(26, global::pbs.LoginZoneList.Parser);
    private readonly pbc::RepeatedField<global::pbs.LoginZoneList> zonelist_ = new pbc::RepeatedField<global::pbs.LoginZoneList>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::pbs.LoginZoneList> Zonelist {
      get { return zonelist_; }
    }

    /// <summary>Field number for the "maildatalist" field.</summary>
    public const int MaildatalistFieldNumber = 4;
    private static readonly pb::FieldCodec<global::pbs.MailData> _repeated_maildatalist_codec
        = pb::FieldCodec.ForMessage(34, global::pbs.MailData.Parser);
    private readonly pbc::RepeatedField<global::pbs.MailData> maildatalist_ = new pbc::RepeatedField<global::pbs.MailData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::pbs.MailData> Maildatalist {
      get { return maildatalist_; }
    }

    /// <summary>Field number for the "iteminfolist" field.</summary>
    public const int IteminfolistFieldNumber = 5;
    private static readonly pb::FieldCodec<global::pbs.BaseItemInfo> _repeated_iteminfolist_codec
        = pb::FieldCodec.ForMessage(42, global::pbs.BaseItemInfo.Parser);
    private readonly pbc::RepeatedField<global::pbs.BaseItemInfo> iteminfolist_ = new pbc::RepeatedField<global::pbs.BaseItemInfo>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::pbs.BaseItemInfo> Iteminfolist {
      get { return iteminfolist_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ReqTestMsg);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ReqTestMsg other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Account != other.Account) return false;
      if (Password != other.Password) return false;
      if(!zonelist_.Equals(other.zonelist_)) return false;
      if(!maildatalist_.Equals(other.maildatalist_)) return false;
      if(!iteminfolist_.Equals(other.iteminfolist_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Account.Length != 0) hash ^= Account.GetHashCode();
      if (Password.Length != 0) hash ^= Password.GetHashCode();
      hash ^= zonelist_.GetHashCode();
      hash ^= maildatalist_.GetHashCode();
      hash ^= iteminfolist_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Account.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Account);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Password);
      }
      zonelist_.WriteTo(output, _repeated_zonelist_codec);
      maildatalist_.WriteTo(output, _repeated_maildatalist_codec);
      iteminfolist_.WriteTo(output, _repeated_iteminfolist_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Account.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Account);
      }
      if (Password.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Password);
      }
      size += zonelist_.CalculateSize(_repeated_zonelist_codec);
      size += maildatalist_.CalculateSize(_repeated_maildatalist_codec);
      size += iteminfolist_.CalculateSize(_repeated_iteminfolist_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ReqTestMsg other) {
      if (other == null) {
        return;
      }
      if (other.Account.Length != 0) {
        Account = other.Account;
      }
      if (other.Password.Length != 0) {
        Password = other.Password;
      }
      zonelist_.Add(other.zonelist_);
      maildatalist_.Add(other.maildatalist_);
      iteminfolist_.Add(other.iteminfolist_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Account = input.ReadString();
            break;
          }
          case 18: {
            Password = input.ReadString();
            break;
          }
          case 26: {
            zonelist_.AddEntriesFrom(input, _repeated_zonelist_codec);
            break;
          }
          case 34: {
            maildatalist_.AddEntriesFrom(input, _repeated_maildatalist_codec);
            break;
          }
          case 42: {
            iteminfolist_.AddEntriesFrom(input, _repeated_iteminfolist_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class ReqTestG2DMsg : pb::IMessage<ReqTestG2DMsg> {
    private static readonly pb::MessageParser<ReqTestG2DMsg> _parser = new pb::MessageParser<ReqTestG2DMsg>(() => new ReqTestG2DMsg());
    private pb::UnknownFieldSet _unknownFields;
    public const ulong HashID = 0xC1ABB8D9FDE16843;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ReqTestG2DMsg> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::pbs.TestReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReqTestG2DMsg() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReqTestG2DMsg(ReqTestG2DMsg other) : this() {
      account_ = other.account_;
      zonelist_ = other.zonelist_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReqTestG2DMsg Clone() {
      return new ReqTestG2DMsg(this);
    }

    /// <summary>Field number for the "account" field.</summary>
    public const int AccountFieldNumber = 1;
    private string account_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Account {
      get { return account_; }
      set {
        account_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "zonelist" field.</summary>
    public const int ZonelistFieldNumber = 2;
    private static readonly pb::FieldCodec<global::pbs.LoginZoneList> _repeated_zonelist_codec
        = pb::FieldCodec.ForMessage(18, global::pbs.LoginZoneList.Parser);
    private readonly pbc::RepeatedField<global::pbs.LoginZoneList> zonelist_ = new pbc::RepeatedField<global::pbs.LoginZoneList>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::pbs.LoginZoneList> Zonelist {
      get { return zonelist_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ReqTestG2DMsg);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ReqTestG2DMsg other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Account != other.Account) return false;
      if(!zonelist_.Equals(other.zonelist_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Account.Length != 0) hash ^= Account.GetHashCode();
      hash ^= zonelist_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Account.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Account);
      }
      zonelist_.WriteTo(output, _repeated_zonelist_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Account.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Account);
      }
      size += zonelist_.CalculateSize(_repeated_zonelist_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ReqTestG2DMsg other) {
      if (other == null) {
        return;
      }
      if (other.Account.Length != 0) {
        Account = other.Account;
      }
      zonelist_.Add(other.zonelist_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Account = input.ReadString();
            break;
          }
          case 18: {
            zonelist_.AddEntriesFrom(input, _repeated_zonelist_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class ReqTestD2GMsg : pb::IMessage<ReqTestD2GMsg> {
    private static readonly pb::MessageParser<ReqTestD2GMsg> _parser = new pb::MessageParser<ReqTestD2GMsg>(() => new ReqTestD2GMsg());
    private pb::UnknownFieldSet _unknownFields;
    public const ulong HashID = 0xE0DBEBA4D24BEEB7;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ReqTestD2GMsg> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::pbs.TestReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReqTestD2GMsg() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReqTestD2GMsg(ReqTestD2GMsg other) : this() {
      account_ = other.account_;
      zonelist_ = other.zonelist_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReqTestD2GMsg Clone() {
      return new ReqTestD2GMsg(this);
    }

    /// <summary>Field number for the "account" field.</summary>
    public const int AccountFieldNumber = 1;
    private string account_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Account {
      get { return account_; }
      set {
        account_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "zonelist" field.</summary>
    public const int ZonelistFieldNumber = 2;
    private static readonly pb::FieldCodec<global::pbs.LoginZoneList> _repeated_zonelist_codec
        = pb::FieldCodec.ForMessage(18, global::pbs.LoginZoneList.Parser);
    private readonly pbc::RepeatedField<global::pbs.LoginZoneList> zonelist_ = new pbc::RepeatedField<global::pbs.LoginZoneList>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::pbs.LoginZoneList> Zonelist {
      get { return zonelist_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ReqTestD2GMsg);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ReqTestD2GMsg other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Account != other.Account) return false;
      if(!zonelist_.Equals(other.zonelist_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Account.Length != 0) hash ^= Account.GetHashCode();
      hash ^= zonelist_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Account.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Account);
      }
      zonelist_.WriteTo(output, _repeated_zonelist_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Account.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Account);
      }
      size += zonelist_.CalculateSize(_repeated_zonelist_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ReqTestD2GMsg other) {
      if (other == null) {
        return;
      }
      if (other.Account.Length != 0) {
        Account = other.Account;
      }
      zonelist_.Add(other.zonelist_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Account = input.ReadString();
            break;
          }
          case 18: {
            zonelist_.AddEntriesFrom(input, _repeated_zonelist_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class RspTestMsg : pb::IMessage<RspTestMsg> {
    private static readonly pb::MessageParser<RspTestMsg> _parser = new pb::MessageParser<RspTestMsg>(() => new RspTestMsg());
    private pb::UnknownFieldSet _unknownFields;
    public const ulong HashID = 0x2D167AE2C41D24DB;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RspTestMsg> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::pbs.TestReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RspTestMsg() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RspTestMsg(RspTestMsg other) : this() {
      zonelist_ = other.zonelist_.Clone();
      maildatalist_ = other.maildatalist_.Clone();
      iteminfolist_ = other.iteminfolist_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RspTestMsg Clone() {
      return new RspTestMsg(this);
    }

    /// <summary>Field number for the "zonelist" field.</summary>
    public const int ZonelistFieldNumber = 1;
    private static readonly pb::FieldCodec<global::pbs.LoginZoneList> _repeated_zonelist_codec
        = pb::FieldCodec.ForMessage(10, global::pbs.LoginZoneList.Parser);
    private readonly pbc::RepeatedField<global::pbs.LoginZoneList> zonelist_ = new pbc::RepeatedField<global::pbs.LoginZoneList>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::pbs.LoginZoneList> Zonelist {
      get { return zonelist_; }
    }

    /// <summary>Field number for the "maildatalist" field.</summary>
    public const int MaildatalistFieldNumber = 2;
    private static readonly pb::FieldCodec<global::pbs.MailData> _repeated_maildatalist_codec
        = pb::FieldCodec.ForMessage(18, global::pbs.MailData.Parser);
    private readonly pbc::RepeatedField<global::pbs.MailData> maildatalist_ = new pbc::RepeatedField<global::pbs.MailData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::pbs.MailData> Maildatalist {
      get { return maildatalist_; }
    }

    /// <summary>Field number for the "iteminfolist" field.</summary>
    public const int IteminfolistFieldNumber = 3;
    private static readonly pb::FieldCodec<global::pbs.BaseItemInfo> _repeated_iteminfolist_codec
        = pb::FieldCodec.ForMessage(26, global::pbs.BaseItemInfo.Parser);
    private readonly pbc::RepeatedField<global::pbs.BaseItemInfo> iteminfolist_ = new pbc::RepeatedField<global::pbs.BaseItemInfo>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::pbs.BaseItemInfo> Iteminfolist {
      get { return iteminfolist_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RspTestMsg);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RspTestMsg other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!zonelist_.Equals(other.zonelist_)) return false;
      if(!maildatalist_.Equals(other.maildatalist_)) return false;
      if(!iteminfolist_.Equals(other.iteminfolist_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= zonelist_.GetHashCode();
      hash ^= maildatalist_.GetHashCode();
      hash ^= iteminfolist_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      zonelist_.WriteTo(output, _repeated_zonelist_codec);
      maildatalist_.WriteTo(output, _repeated_maildatalist_codec);
      iteminfolist_.WriteTo(output, _repeated_iteminfolist_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += zonelist_.CalculateSize(_repeated_zonelist_codec);
      size += maildatalist_.CalculateSize(_repeated_maildatalist_codec);
      size += iteminfolist_.CalculateSize(_repeated_iteminfolist_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RspTestMsg other) {
      if (other == null) {
        return;
      }
      zonelist_.Add(other.zonelist_);
      maildatalist_.Add(other.maildatalist_);
      iteminfolist_.Add(other.iteminfolist_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            zonelist_.AddEntriesFrom(input, _repeated_zonelist_codec);
            break;
          }
          case 18: {
            maildatalist_.AddEntriesFrom(input, _repeated_maildatalist_codec);
            break;
          }
          case 26: {
            iteminfolist_.AddEntriesFrom(input, _repeated_iteminfolist_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
